
host: 'api.moc.thoth-station.ninja'
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: 'rhel:8.0'
    operating_system:
      name: 'rhel'
      version: '8.0'
    python_version: '3.6'
    recommendation_type: STABLE

managers:
  - name: thoth-advise
    configuration:
      labels: [bot, kebechet]
  - name: thoth-provenance
    configuration:
      labels: [bot, kebechet]